program: exp/lrkd-deit-tiny.sh
command:
  - bash
  - ${program}
  - ${args}
method: bayes  
metric:
  name: val_acc1 
  goal: maximize
parameters:
  lrkd_rank:
    values: [16,32,64,128]
  lrkd_alpha:
    distribution: uniform
    min: 0.1
    max: 0.3
  lrkd_beta:
    distribution: uniform
    min: 0.1
    max: 0.3
  lrkd_gamma:
    distribution: uniform
    min: 0.1
    max: 0.3